### ISSUE TITLE
scrollbar on nested elements within a scrollbar element doesn't scroll

### ISSUE THREAD

**Issue by aGeNET** [jnicol/trackpad-scroll-emulator#13]
If I combine the fullpage scrolling with scrollable boxes, the drag-handle is sticky on top of the boxes.
Only the fullpage container is correctly scrolling on mouseinteraction.
The boxcontent ist scrolling on mouseinteraction but the drag-handle remains on top of the box container.

There are maybe referencing issues on the eventtracking and drag-handle moving.

**Comment by jnicol** [comment]
Nested scrollables are fixed in a7aa39c2b20d36edaf99108cec17257d24401107
