### ISSUE TITLE
any way to nest this?

### ISSUE THREAD

**Issue by frumbert** [jnicol/trackpad-scroll-emulator#15]
For instance, an outer container uses vertical scrollbar, and an inner container uses horizontal scrolling. Doesn't seem to be possible. Perhaps clarify this in the readme statement regarding using both?

**Comment by idanhen** [comment]
I fixed this issue and pushed a fix - if they will accept it, it will work for you.

if you want the fix - PM me and i will tell you what to do .

**Comment by jnicol** [comment]
Fixed in a7aa39c2b20d36edaf99108cec17257d24401107
