### ISSUE TITLE
scrollbar not support scrollbar inside scrollbar

### ISSUE THREAD

**Issue by idanhen** [jnicol/trackpad-scroll-emulator#18]
I create a textarea with scroll bar inside a dynamic div with scrollbar.

the inner textarea is not changing the scrollbar. I also found how to fix it:

LINE 36: var $contentEl = $el.find('.tse-content:first');
LINE 61: $scrollbarEl = $el.find('.tse-scrollbar:first');
LINE 62: $dragHandleEl = $el.find('.drag-handle:first');
LINE 67: $scrollContentEl = $el.find('.tse-scroll-content:first');

**Comment by idanhen** [comment]
I commited the fix

**Comment by jnicol** [comment]
Thanks - look good. I have merged your pull request.
